jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://172.17.28.129:3306/P365MyTest
  username: root
  password: Arcsoft01
  user:
    name: zhangsan
    age: 21
    language:
      - java
      - php
      - python


server:
  port: 8088
  servlet:
    path: /
logging:
  level:
    cn.itcast: debug
#    org.springframework: debug
